services:
  - type: web
    name: legal-consultation-rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /health